# Site Settings
title:              CLRS Solutions
author:             Atekihcan
email:              contact@atekihcan.com
description:        "Solutions to exercises and problems of Introduction to Algorithms by CLRS (Cormen, Leiserson, Rivest, and Stein) with intuitive explanations, step-by-step proofs, and working Python code"
keywords:           "CLRS, solutions, algorithms, Cormen"

# Handling Reading
exclude:            ['README.md', 'LICENSE.md', 'disqus_comments_archive.md']

# Conversion
markdown:           kramdown
kramdown:
    input:          GFM
    highlighter:    rouge

# Serving
url:                "https://atekihcan.github.io"
baseurl:            "/CLRS"

# Outputting
permalink:          /:title/

# Google Analytics
google_analytics_id: "G-81ZV6JSJ2J"

# Collection
collections:
  solutions:
    output: true
    permalink: /:path/

# Default Values
defaults:
  -
    scope:
      path: ""
      type: "solutions"
    values:
      layout: "post"
      author:     "Atekihcan"
